### ISSUE TITLE
Remove bidict.invert()

### ISSUE THREAD

**Issue by lordmauve** [jab/bidict#20]
The undocumented ``bidict.invert()`` appears to perform an "invert-in-place". This seems superfluous given ``.inv``; but naive use of this method could cause significant confusion about what state a bidict is in at what point in a program (consider beginners in particular). Without this there's no risk of holding a reference to a bidict that flip-flops in semantics.

A more expert programmer who wanted to do an in-place replacement of values, could use the same kind of approach as to mutate a normal dict in-place, eg:

    vals = list(d.items())    
    d.clear()
    d.inv.update(vals)

(Background: I work on a very large project (thousands of developers) where we see every type of mistake under the sun, and I can imagine this accidentally/foolishly being used to mutate global "constant" state causing hard-to-diagnose problems.)

**Comment by jab** [comment]
> The undocumented...

Thanks for flagging this. `invert` used to be documented, but its docstring was removed when bidict's doctests were ported to external files. (This particular one ended up [here](https://github.com/jab/bidict/blob/5d30fc7610fe17cbefa800cbaa744764adc2a121/tests/test_bidict.bidict.txt#L108).)

> naive use of this method could cause significant confusion about what state a bidict is in at what point in a program

(Not moved much by this point. By analogy, we have `reversed(my_list)` as well as `my_list.reverse()`; up to the caller to use responsibly.)

> ...who wanted to do an in-place replacement of values...

Instead of the snippet you give above, this is a cleaner way to replace a bidict with its inverse:
```python
>>> b = b.inv
```

Since this communicates the intention just as clearly as `b.invert()`, and is no less efficient than what `invert` was doing under the hood, I agree there's no reason to keep the `invert` method. Removed in  d7551db. Thanks for the suggestion.

> (Background: I work on a very large project (thousands of developers)

Are you using bidict in your very large project? Always curious to hear more about my users' use cases, in case you'd like to share. And if bidict is helping you in work you're getting paid for, please consider supporting bidict with a monetary contribution or asking your employer to do the same!

https://github.com/jab/bidict/blob/master/CONTRIBUTING.rst#other-ways-to-contribute

**Comment by lordmauve** [comment]
``b = b.inv`` doesn't change an object in-place (such that existing references to it are updated).

We're not using bidict at this point. I'm just considering whether I can make a recommendation for its inclusion in the project and flagging up some issues that I would expect people to bring up. Due to the size of the project we end up being extremely careful about what we include, and a lot of questions get asked before any action would be taken.

**Comment by jab** [comment]
> `b = b.inv` doesn't change an object in-place (such that existing references to it are updated).

Yes, thank you. Meant to say, this must be done for every reference to `b`.

> ...I'm just considering whether I can make a recommendation...

Gotcha. I'm interested to discuss any other concerns, and hope bidict can accommodate your use case. Thanks again for your thoughtful feedback.
