### ISSUE TITLE
is there any simple way to run tests on windows?

### ISSUE THREAD

**Issue by bialix** [jab/bidict#39]
I want to check whether your project is compatible with python 3.3. Your classifier only list 3.4 and 3.5.

I've installed py.test - no luck to run tests:

```
D:\work\OpenSource\bidict.git>py.test tests
usage: py.test [options] [file_or_dir] [file_or_dir] [...]
py.test: error: unrecognized arguments: --benchmark-save-data --benchmark-autosave --benchmark-group-by=name --benchmark-compare
  inifile: D:\work\OpenSource\bidict.git\pytest.ini
  rootdir: D:\work\OpenSource\bidict.git

```

I've tried `python setup.py tests` - that commands downloads half of pypi, and then said:

```
----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

I've installed tox because that's what your contributing guide seems to suggest me. It said:

`OSError: [WinError 193] %1 is not Win32 application`

(that tried to run test.sh under the hood).

What I should try next?

**Comment by jab** [comment]
> is there any simple way to run tests on windows?

Sure. I had an old Windows 10 VM kicking around, so I installed Python 3.3 on it using http://www.python.org/ftp/python/3.3.5/python-3.3.5.amd64.msi, then tested the following, and it worked like a charm:

1. `git clone https://github.com/jab/bidict.git`
1. `cd bidict`
1. `python -m pip install -e .[dev]`
1. `python -m pytest`

```
IEUser@IE11WIN10 MINGW64 ~/bidict (master)
$ /c/Python33/python.exe -m pytest
============================= test session starts =============================
platform win32 -- Python 3.3.5, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- C:\Python33\python.exe
cachedir: .cache
benchmark: 3.0.0 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=5.00us max_time=1.00s calibration_precision=10 warmup=False warmup_iterations=100000)
rootdir: C:\Users\IEUser\bidict, inifile: pytest.ini
plugins: hypothesis-3.4.2, benchmark-3.0.0, cov-2.2.1
collecting ... collected 233 items

bidict/util.py::bidict.util.pairs PASSED
tests/test_benchmark.py::test_put_nodup[bidict] PASSED
tests/test_benchmark.py::test_put_nodup[orderedbidict] PASSED
tests/test_benchmark.py::test_put_withdup[bidict] PASSED
tests/test_benchmark.py::test_put_withdup[orderedbidict] PASSED
tests/test_benchmark.py::test_update_nodup[bidict] PASSED
tests/test_benchmark.py::test_update_nodup[orderedbidict] PASSED
tests/test_benchmark.py::test_update_withdup[bidict] PASSED
tests/test_benchmark.py::test_update_withdup[orderedbidict] PASSED
tests/test_benchmark.py::test_forceupdate_withdup[bidict] PASSED
tests/test_benchmark.py::test_forceupdate_withdup[orderedbidict] PASSED
tests/test_bidict.txt PASSED
tests/test_frozenbidict.txt PASSED
tests/test_hypothesis.py::test_equality[bidict] PASSED
tests/test_hypothesis.py::test_equality[loosebidict] PASSED
tests/test_hypothesis.py::test_equality[looseorderedbidict] PASSED
tests/test_hypothesis.py::test_equality[orderedbidict] PASSED
tests/test_hypothesis.py::test_equality[frozenbidict] PASSED
tests/test_hypothesis.py::test_equality[frozenorderedbidict] PASSED
tests/test_hypothesis.py::test_bidirectional_mappings[bidict] PASSED
tests/test_hypothesis.py::test_bidirectional_mappings[loosebidict] PASSED
tests/test_hypothesis.py::test_bidirectional_mappings[looseorderedbidict] PASSED
tests/test_hypothesis.py::test_bidirectional_mappings[orderedbidict] PASSED
tests/test_hypothesis.py::test_bidirectional_mappings[frozenbidict] PASSED
tests/test_hypothesis.py::test_bidirectional_mappings[frozenorderedbidict] PASSE                                                                                 D
tests/test_hypothesis.py::test_consistency_after_mutation[bidict-0-clear] PASSED
...
========= 221 passed, 12 skipped, 1 pytest-warnings in 40.26 seconds ==========
```

So that also demonstrates that the tests pass with Python 3.3.

Looks like you tried running the tests with `py.test tests`. Note that there is already a pytest.ini file which specifies the test paths (and other options), so there's no need to pass the `tests` argument.

Based on the `py.test: error: unrecognized arguments: --benchmark-save-data...` error you're seeing, perhaps pytest-benchmark did not get installed successfully either? That should have been installed by the `pip install -e .[dev]` command (thanks to `extras_require` and `tests_require` in the setup.py).

Regarding Python 3.3, in case you didn't see it in https://bidict.readthedocs.io/en/master/changelog.html#id2, I no longer support 3.3 officially (though it may continue to work). That was inspired by [this message](https://groups.google.com/d/msg/hypothesis-users/8FVs--1yUl4/FFUmY7HfHgAJ) by the author of Hypothesis:

> I dropped 3.3 support in 2.0, it just unofficially worked.
>
> I've just accepted a patch to add the enum34 dependency on 3.3 too, but be warned that you are in unofficial support territory and there may be dragons*. :-)
>
> My official recommendation is to do one of not run Hypothesis based tests on 3.3 or to also drop 3.3 support because barely anyone actually cares about 3.3, but you could also just install enum34 for your tests.

Hope this helps, thanks for your interest in bidict, and welcome to the community! What are you using bidict for? I'm always interested in getting to know bidict's users and their use cases better, and supporting them as much as I can, so feel free to keep me posted on how things are working for you.

**Comment by jab** [comment]
![screen shot 2016-08-11 at 09 41 04](https://cloud.githubusercontent.com/assets/64992/17591059/5cc5547e-5faa-11e6-88ad-0cd1f74ae96c.png)

**Comment by jab** [comment]
@bialix Any luck?

**Comment by bialix** [comment]
Yes, thanks

(*) Outliers: 1 Standard Deviation from Mean; 1.5 IQR (InterQuartile Range)
from 1st Quartile and 3rd Quartile.
========= 221 passed, 12 skipped, 1 pytest-warnings in 34.18 seconds
==========

2016-08-15 6:20 GMT+03:00 jab <notifications@github.com>:

**Comment by jab** [comment]
Great.

**Comment by jab** [comment]
https://ci.appveyor.com/project/jab/bidict
